name: 'build'

on:
  push:

env:
  ACTIONS_STEP_DEBUG: true


jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup tfvm
      uses: cbuschka/setup-tfvm@83227a789f9e29d90a218bf8d20c9d8cde9b8b5a
      env:
        ACTIONS_STEP_DEBUG: true

    - name: write .terraform-version file
      run: echo "v1.3.4" > .terraform-version

    - name: run tfvm
      run: tfvm info

    - name: run terraform version
      run: terraform version
